version: '3.1'

services:
  postgres:
    image: postgres:11.9-alpine
    restart: always
    ports:
      - 5432:5432
    volumes:
      - ./docker-entrypoint-initdb.d/:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: postgres